name: Bogus CI/CD Pipeline

on: [push, pull_request]

jobs:
  ci:
    runs-on: windows-latest
    outputs:
      new_version: ${{ steps.tag_generator.outputs.new_version }}
    steps:
      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - if: github.repository_owner == github.actor
        name: Activate TestSpace tool
        id: testspace_tool
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}
          token: ${{ secrets.TESTSPACE_TOKEN }}

      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Bump release version and create release tag
        id: tag_generator
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false

      - if: github.repository_owner == github.actor
        name: Cache SonarCloud packages
        id: cache_sonar_packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - if: github.repository_owner == github.actor
        name: Cache SonarCloud scanner
        id: cache_sonar_scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - if: github.repository_owner == github.actor && steps.cache_sonar_scanner.outputs.cache-hit != 'true'
        name: Install SonarCloud scanner
        id: install_sonar_scanner
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - if: github.repository_owner == github.actor
        name: Lowercase string generator
        id: lowercase_string_gen
        shell: powershell
        run: |
          $LOWERCASE_OWNER = "${{ github.repository_owner }}".ToLower()
          echo "::set-output name=owner_name::$LOWERCASE_OWNER"

      - if: github.repository_owner == github.actor
        name: Initialize SonarCloud scanner
        id: init_sonar_scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: .\.sonar\scanner\dotnet-sonarscanner begin /k:"${{ github.repository_owner }}_${{ github.event.repository.name }}" /o:"${{ steps.lowercase_string_gen.outputs.owner_name }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      - name: Install .NET dependencies
        id: install_dotnet_dependencies
        shell: powershell
        run: dotnet tool restore

      - name: Initialize CodeQL
        id: init_codeql
        uses: github/codeql-action/init@v1
        with:
          queries: security-extended, security-and-quality

      - name: Build project
        id: build_project
        shell: powershell
        run: dotnet fake run Source\Builder\build.fsx target ci
        env:
          FORCE_VERSION: ${{ steps.tag_generator.outputs.new_version }}

      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Upload package artifact
        id: up_package_artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: __package/

      - name: Run project tests
        id: run_project_tests
        shell: powershell
        run: dotnet fake run Source\Builder\build.fsx target test

      - if: github.repository_owner == github.actor && always()
        name: Push result to Testspace server
        id: push_to_testspace
        shell: powershell
        run: |
          testspace "__test/results.xml{Source/Bogus.Tests}"

      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Upload package artifact
        id: up_test_results_artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: __test/

      - if: github.repository_owner == github.actor
        name: Send SonarCloud results
        id: send_sonar_results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Perform CodeQL Analysis
        id: analyze_codeql
        uses: github/codeql-action/analyze@v1

  cd:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && needs.ci.outputs.new_version != ''
    # "This job will execute when the workflow is triggered on a 'push event', the target branch is 'master' and the commit is intended to be a release." #
    needs: ci
    runs-on: windows-latest
    env:
      NEW_VERSION: ${{ needs.ci.outputs.new_version }}
      NEW_TAG: v${{ needs.ci.outputs.new_version }}
    steps:
      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v2

      - name: Download and extract package artifact
        id: dl_package_artifact
        uses: actions/download-artifact@v2
        with:
          name: Package
          path: __package/

      - name: Download and extract test results artifact
        id: dl_test_results_artifact
        uses: actions/download-artifact@v2
        with:
          name: TestResults
          path: __test/

      - name: Publish *.nupkg on NuGet
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
             PROJECT_FILE_PATH: 'Source/Bogus/Bogus.csproj'
             TAG_COMMIT: true
             NUGET_KEY: ${{secrets.NUGET_TOKEN}}
             PACKAGE_NAME: Bogus.${{ env.NEW_VERSION }}.nupkg

      - name: Create and publish release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: Release ${{ env.NEW_TAG }}
          body: "[CHANGE LOG](HISTORY.md)"

      - name: Upload Bogus.zip as release asset
        id: upload_bogus_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: __package/Bogus.zip
          asset_name: Bogus.zip
          asset_content_type: application/zip

      - name: Upload Bogus.snupkg as release asset
        id: upload_bogus_snupkg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: __package/Bogus.${{ env.NEW_VERSION }}.snupkg
          asset_name: Bogus.${{ env.NEW_VERSION }}.snupkg
          asset_content_type: application/snupkg

      - name: Upload Bogus.nupkg as release asset
        id: upload_bogus_nupkg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: __package/Bogus.${{ env.NEW_VERSION }}.nupkg
          asset_name: Bogus.${{ env.NEW_VERSION }}.nupkg
          asset_content_type: application/nupkg

      - name: Upload internal test results as release asset
        id: upload_internal_test_results
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: __test/results.xml
          asset_name: results.xml
          asset_content_type: application/xml
